# Generated by Django 2.2.5 on 2020-04-25 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unicorn', 'Unicorn')], default='Unicorn', max_length=10)),
                ('image', models.ImageField(default='thehideout.jpg', upload_to='profile_pics')),
                ('user_group', models.CharField(choices=[('Pawn', 'Pawn'), ('Rook', 'Rook'), ('Knight', 'Knight'), ('Bishop', 'Bishop'), ('Queen', 'Queen'), ('King', 'King')], default='Pawn', max_length=10)),
                ('FB', models.CharField(max_length=80, null=True)),
                ('IG', models.CharField(max_length=80, null=True)),
                ('TW', models.CharField(max_length=80, null=True)),
                ('school', models.CharField(default='Secret!', max_length=100)),
                ('year_in_school', models.CharField(choices=[('Freshman', 'Freshman'), ('Sophomore', 'Sophomore'), ('Junior', 'Junior'), ('Senior', 'Senior'), ('Graduate', 'Graduate')], default='Freshman', max_length=10)),
                ('quote', models.CharField(max_length=300)),
                ('about_me', models.TextField(blank=True)),
                ('date_registered', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
