# Generated by Django 2.2.5 on 2020-04-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='thehideout.jpg', upload_to='user_directory_path'),
        ),
    ]
