# Generated by Django 2.2.5 on 2020-04-25 16:34

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200425_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='thehideout.jpg', upload_to=users.models.Profile.dp_directory_path),
        ),
    ]
