# Generated by Django 3.0.5 on 2020-10-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200425_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reach_me_intro',
            field=models.CharField(default='You can reach me thru: ', max_length=300),
        ),
    ]
