# Generated by Django 3.0.5 on 2020-10-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_reach_me_intro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reach_me_intro',
            field=models.TextField(default='You can reach me thru: '),
        ),
    ]
