# Generated by Django 2.2.5 on 2020-04-26 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loungeunsentletters',
            old_name='owner',
            new_name='author',
        ),
    ]
