# Generated by Django 2.2.5 on 2020-04-26 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0002_auto_20200426_0101'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loungeunsentletters',
            old_name='date_uploaded',
            new_name='date_posted',
        ),
    ]
